version: "3"
services:
  fastapi_uvicorn:
    build:
      context: .
    container_name: cube_python_fastapi_uvicorn_fastapi
    environment:
      - OTEL_SERVICE_NAME=cube_sample_python_fastapi_uvicorn
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip

      # print traces on console
      - OTEL_LOG_LEVEL=debug
      # send traces to CubeAPM
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_python_fastapi_uvicorn_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_python_fastapi_uvicorn_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_python_fastapi_uvicorn_redis

volumes:
  cube_python_fastapi_uvicorn_mysql:
